import { ArrowRight, CalendarDays, Check, ClipboardList, FileText, LayoutDashboard, MailCheck, MessageSquareText, MonitorSmartphone, Sparkles, UserRoundCheck, WandSparkles } from 'lucide-react';
import { ButtonLink } from '@/components/ui';
import { ContactForm } from '@/components/contact-form';
import { site } from '@/lib/site';

const audiences=['Restaurants','Cabinets professionnels','Immobilier','Artisans','Services locaux','Conseil','Recrutement','Formation'];
const offers=[
 {n:'01',icon:MonitorSmartphone,title:'Présence en ligne',description:'Un site clair, soigné et facile à utiliser sur mobile. Vos visiteurs comprennent votre activité et savent comment vous contacter.',example:'Présenter votre activité · inspirer confiance · être trouvé localement'},
 {n:'02',icon:CalendarDays,title:'Demandes & rendez-vous',description:'Un parcours qui permet de réserver, demander un devis ou préciser son besoin avant le premier échange.',example:'Réservation · prise de rendez-vous · demandes mieux qualifiées'},
 {n:'03',icon:LayoutDashboard,title:'Espaces & outils métier',description:'Un espace client ou un outil interne simple pour suivre les dossiers, organiser les demandes et retrouver l’information.',example:'Suivi de dossiers · espace client · tableau de bord'},
 {n:'04',icon:WandSparkles,title:'Automatisation',description:'Les confirmations, notifications et tâches répétitives peuvent se faire automatiquement, sans complexifier votre travail.',example:'Moins de saisies · informations centralisées · suivi simplifié'},
];
const situations=[
 'Vos clients doivent vous appeler pour presque tout.',
 'Les demandes reçues par email manquent d’informations.',
 'Votre site présente votre activité, mais génère peu d’actions.',
 'Vous jonglez entre plusieurs fichiers pour suivre les demandes.',
 'Vous redemandez souvent les mêmes renseignements.',
 'Vos clients ne savent pas où en est leur dossier.',
];
const steps=[
 ['01','On échange','Je comprends votre activité et ce qui vous fait perdre du temps.'],
 ['02','Je propose','Je recommande une solution utile, avec un périmètre clair.'],
 ['03','Je construis','Je développe et vous montre l’avancement régulièrement.'],
 ['04','On met en ligne','Je prépare la mise en service et reste disponible pour la suite.'],
];
const strengths=[
 ['Un seul interlocuteur','Vous échangez directement avec la personne qui conçoit et développe votre solution.'],
 ['Juste ce qu’il faut','Pas de plateforme démesurée lorsqu’un outil simple suffit.'],
 ['Au-delà de la page','Je peux créer les espaces, données et automatisations qui font fonctionner le site.'],
 ['Une base solide','Ma formation d’ingénieur et mon expérience web et backend soutiennent la réalisation.'],
];
function Journey(){return <div className="journey" aria-label="Exemple de parcours : visiteur, demande structurée, suivi"><div className="journey-top"><span>UN SITE QUI REND SERVICE</span><span className="journey-dot"/></div><div className="journey-step"><span className="journey-icon"><UserRoundCheck size={22}/></span><div><small>01 / VOTRE VISITEUR</small><strong>Il découvre votre activité.</strong><p>Une présentation claire, sur téléphone comme sur ordinateur.</p></div></div><div className="journey-line"/><div className="journey-step featured"><span className="journey-icon"><ClipboardList size={22}/></span><div><small>02 / SA DEMANDE</small><strong>Il passe à l’action.</strong><p>Rendez-vous, devis ou formulaire adapté à votre métier.</p></div></div><div className="journey-line"/><div className="journey-step"><span className="journey-icon"><MailCheck size={22}/></span><div><small>03 / VOTRE QUOTIDIEN</small><strong>Vous recevez les bonnes informations.</strong><p>De quoi répondre plus vite et mieux vous organiser.</p></div></div><div className="journey-bottom"><Check size={17}/> Un parcours utile pour vous et vos clients</div></div>}
function Example(){return <div className="example"><div className="example-header"><span>EXEMPLE CONCRET</span><span>DE LA VISITE À L’ACTION</span></div><div className="example-row"><span className="example-icon"><FileText size={23}/></span><div><small>UN SITE CLASSIQUE</small><strong>« Demandez un devis »</strong><p>Le client envoie un message libre. Il manque souvent des détails.</p></div></div><div className="example-divider"><ArrowRight size={18}/></div><div className="example-row active"><span className="example-icon"><ClipboardList size={23}/></span><div><small>UNE SOLUTION ADAPTÉE</small><strong>Une demande déjà structurée</strong><p>Service, adresse, photos et disponibilités : vous recevez les éléments utiles dès le départ.</p></div></div></div>}
export default function Home(){const schema={'@context':'https://schema.org','@type':'ProfessionalService',name:site.name,description:site.description,areaServed:{'@type':'AdministrativeArea',name:'France'},founder:{'@type':'Person',name:site.owner},...(site.email?{email:site.email}:{})};return <main id="main"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/>
 <section id="accueil" className="hero container"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-line"/> OUAKRIM IT SERVICES · TOULOUSE</p><h1>Un site utile.<br/><span>Une activité plus simple.</span></h1><p className="hero-intro">Je crée votre présence en ligne et les outils qui vont avec : rendez-vous, demandes de devis, espaces clients ou automatisations.</p><p className="hero-detail">Pour les petites entreprises et indépendants qui veulent mieux accueillir leurs clients et gagner du temps.</p><div className="cta-row"><ButtonLink href="#contact">Parler de votre projet</ButtonLink><ButtonLink href="#services" secondary>Découvrir les services</ButtonLink></div><p className="hero-signature">Othman Ait Ouakrim · Votre interlocuteur direct</p></div><Journey/></section>
 <section className="audience-band"><div className="container"><p className="eyebrow">POUR LES STRUCTURES À TAILLE HUMAINE</p><div className="audience-list">{audiences.map(a=><span key={a}>{a}</span>)}</div></div></section>
 <section id="services" className="container section"><div className="section-title"><div><p className="eyebrow">01 / CE QUE JE PEUX METTRE EN PLACE</p><h2>Du premier contact à votre organisation quotidienne.</h2></div><p>Votre site peut présenter votre activité. Il peut aussi vous aider à la gérer.</p></div><div className="services-grid">{offers.map(({icon:Icon,...o})=><article className="service-card" key={o.n}><div className="card-top"><span className="offer-icon"><Icon size={25} aria-hidden="true"/></span><span>{o.n}</span></div><h3>{o.title}</h3><p>{o.description}</p><p className="offer-example">{o.example}</p></article>)}</div></section>
 <section id="situations" className="section situations-section"><div className="container situations-layout"><div><p className="eyebrow">02 / VOTRE QUOTIDIEN</p><h2>Vous vous reconnaissez dans l’une de ces situations ?</h2><p>Souvent, un outil web simple suffit. Le but est d’enlever les étapes inutiles, pas d’ajouter de la complexité.</p><ButtonLink href="#contact" secondary>Parlons de votre situation</ButtonLink></div><ul>{situations.map(s=><li key={s}><span><Check size={17} aria-hidden="true"/></span>{s}</li>)}</ul></div></section>
 <section id="approche" className="container section difference"><div><p className="eyebrow">03 / PLUS QU’UNE VITRINE</p><h2>Votre site peut aussi faire le premier travail.</h2><p>Un formulaire bien pensé recueille les informations utiles avant même votre premier échange. Une réservation évite les allers-retours. Un espace client rend le suivi plus simple.</p><p>Je construis ce qui se voit et ce qui fonctionne derrière, selon votre métier.</p></div><Example/></section>
 <section id="methode" className="section method-section"><div className="container"><div className="section-title"><div><p className="eyebrow">04 / MÉTHODE</p><h2>Un projet, étape par étape.</h2></div></div><div className="method-grid">{steps.map(([n,title,description])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{description}</p></article>)}</div><p className="method-after">Je peux aussi vous accompagner ensuite pour la maintenance et les évolutions.</p></div></section>
 <section className="container section why"><div className="section-title"><div><p className="eyebrow">05 / POURQUOI TRAVAILLER AVEC MOI</p><h2>Une solution à votre mesure.</h2></div></div><div className="why-grid">{strengths.map(([title,description])=><article key={title}><Sparkles size={21} aria-hidden="true"/><h3>{title}</h3><p>{description}</p></article>)}</div></section>
 <section id="a-propos" className="section about-section"><div className="container about"><div><p className="eyebrow">06 / À PROPOS</p><h2>Bonjour,<br/>moi c’est Othman<span>.</span></h2><p className="location">Basé à Toulouse · Projets partout en France</p></div><div><p className="about-lead">Je travaille directement avec les petites entreprises pour créer des solutions web adaptées à leur façon de fonctionner.</p><p>Ingénieur en sciences du numérique, je peux réaliser votre site, puis développer les fonctions utiles derrière : prise de rendez-vous, espace client, suivi ou automatisation. Un seul interlocuteur, de l’idée à la mise en ligne.</p></div></div></section>
 <section id="technologies" className="container technical"><div><p className="eyebrow">07 / UNE BASE TECHNIQUE SOLIDE</p><h2>La simplicité devant. Le savoir-faire derrière.</h2><p>Je m’appuie sur des outils éprouvés pour construire des solutions fiables et faciles à faire évoluer.</p></div><div className="tech-list"><span>Next.js</span><span>React</span><span>TypeScript</span><span>Node.js</span><span>PostgreSQL</span><span>Docker</span></div></section>
 <section className="container final-cta"><div><p className="eyebrow">ON EN PARLE ?</p><h2>Vous avez un besoin en tête ?</h2><p>Expliquez-moi votre activité et ce que vous aimeriez améliorer. Nous verrons ensemble ce qui est utile.</p></div><ButtonLink href="#contact">Discuter de mon projet</ButtonLink></section>
 <section id="contact" className="container section contact"><div><p className="eyebrow">08 / CONTACT</p><h2>Racontez-moi votre besoin.</h2><p>Pas besoin de cahier des charges. Dites-moi simplement comment vous travaillez aujourd’hui.</p><div className="contact-links">{site.email?<a href={'mailto:'+site.email}><MessageSquareText size={19}/> M’écrire directement</a>:<p className="contact-placeholder">[EMAIL À RENSEIGNER]</p>}</div></div><ContactForm/></section>
 </main>}
